services:
  primary:
    build:
      target: primary
    container_name: postgres-streaming-primary
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: primary
    volumes:
      - archiver:/archiver
      - primary-pgdata:/var/lib/postgresql/data
      - ./scripts/init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    command: [ "-c", "config_file=/etc/postgresql/postgresql.primary.conf", "-c", "hba_file=/etc/postgresql/pg_hba.primary.conf" ]
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        timeout: 5s
        retries: 5
        start_period: 5s
    profiles:
      - primary

  standby:
    build:
      target: standby
    container_name: postgres-streaming-standby
    restart: unless-stopped
    volumes:
      - standby-pgdata:/var/lib/postgresql/data
      - archiver:/archiver
    command: [ "-c", "config_file=/etc/postgresql/postgresql.standby.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 5s
      retries: 5
      start_period: 5s
    profiles:
      - standby

volumes:
  archiver:
  primary-pgdata:
  standby-pgdata:
    name: postgres-streaming-standby-pgdata
    external: true

networks:
    default:
        name: postgres-replication-network
        external: true
